### ISSUE TITLE
Bug On RecyBot

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-Mobile#17]
I must Click 2 times on text field to write the question
![Screenshot (1732)](https://github.com/RecyThing/RecyThing-Mobile/assets/102946487/cb514d94-ef9c-4a71-960d-16e9973f8768)

**Comment by sintaayr** [comment]
saran dari mentorku testing nya di real device aja jgn di emulator, karna di real device ngga ada bug ini

**Comment by WingerOfOwl** [comment]
> saran dari mentorku testing nya di real device aja jgn di emulator, karna di real device ngga ada bug ini

sayang nya software buat testing automation ku nggka bisa pake real device :)

**Comment by WingerOfOwl** [comment]
tapi over all masih bisa ku akalin ini
