### ISSUE TITLE
Bug On Detail Point Ku Feature

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-Mobile#22]
If I back to main menu, and i enter to detail point ku again, daily point parameter will be reset
![Screenshot (1785)](https://github.com/RecyThing/RecyThing-Mobile/assets/102946487/5492ec41-ad4c-44ef-b962-3546e0fb2ca1)

**Comment by PuspitaKartika** [comment]
I apologize for this bug as I need an API to fetch points from day 1 to day 7. I have already submitted a request to the BE division and am awaiting the API. A possible solution from my end might involve redesigning the points card.

**Comment by WingerOfOwl** [comment]
@PuspitaKartika it is possible to develop for 2 days ?

**Comment by WingerOfOwl** [comment]
Fixed
