### ISSUE TITLE
Bug On Riwayat Page

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-Mobile#29]
I Redeem Voucher On 10.20 WIB, and On Detail Voucher Show 03.07
![Screenshot (1814)](https://github.com/RecyThing/RecyThing-Mobile/assets/102946487/552c1c01-367c-482c-8ead-305c03d2078a)

**Comment by PuspitaKartika** [comment]
sorry, this bug from BE division, not flutter division, because we only send id voucher & phone number.
