### ISSUE TITLE
Bug On RecyBot On Menu Profile

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-Mobile#9]
When I Click Tanya Recy Button On Menu Profile, I still On Menu Profile, I can't Go to RecyBot
![Screenshot (1711)](https://github.com/RecyThing/RecyThing-Mobile/assets/102946487/d76439d8-c5f7-4020-a095-52ddd632a840)

**Comment by sintaayr** [comment]
resolved
